FROM ubuntu:22.04 AS fds_env

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y gfortran gcc g++ make cmake git wget \
    openmpi-bin libopenmpi-dev python3 python3-pip && \
    apt-get clean